[RAPIDCHANGEATC]

# The map of tool <> pocket
RACK_TABLE=/home/operator/rack_map.txt

# Set to 1 to force all chnages to be handled manually.
# Set IR_DI to -1 to disable probing after tool change
FORCE_ALL_MANUAL_CHANGES = 0
# Probe tool length after manual tool changes. 1 to enable, 0 to disable
PROBE_AFTER_MANUAL_LOAD = 0

NUM_POCKETS = 8

# Position of pocket #1
POCKET_BASE_X = 40
POCKET_BASE_Y = -40

# Distance between pockets (can be negative values)
POCKET_OFFSET_X = 0
POCKET_OFFSET_Y = 2

# Save Z height
#  Before any XY moves, will G53 G0 Z[#<_ini[RAPIDCHANGEATC]SAFE_Z>] to avoid collisions
#  Usually upper Z limit
SAFE_Z = -2

# RPM when loading
ENGAGE_LOAD_RPM = 1700
# Number of strikes during loading, usually 2, but 3 ok.
ENGAGE_LOAD_STRIKES = 1
# RPM when unloading, usually 300RPM higher than load
ENGAGE_UNLOAD_RPM = 1900
# Number of strikes during unloading, usually 1
ENGAGE_UNLOAD_STRIKES = 2

# Machine Z where nut breaks IR, or nut flush with top of changer
ENGAGE_Z_START = -80
# Machine Z at bottom of engage cycle
#  30mm from top of changer
#  ~34mm from IR break
ENGAGE_Z_END = -50
# Feed rate when engaging changer
ENGAGE_FEED = 2000

# motion.digital-in-xx connected to IR sensor
#   -1 disables IR
IR_DI = -1
# motion.digital-out-xx connected to cover output
#   -1 disables cover
COVER_DO = -1

# Toolsetter position
TOOLSET_X = 500
TOOLSET_Y = -45

# Feed rate when searching for end of tool
TOOLSET_SEARCH_FEED = 500
# Max distance to search (negative value on most machines).
# Ensure spindle with empty collet nut won't crash into toolsetter before exceeding this travel.
TOOLSET_SEARCH_DISTANCE = -110
# Backoff distance from search contact to begin latch probe (positive value on most machines)
TOOLSET_LATCH_BACKOFF = 1
# Feed rate when doing more precise latch probe
TOOLSET_LATCH_FEED = 10
# Max distance to do latch probe, should be a little more than (negative value on most machines)
TOOLSET_LATCH_DISTANCE = -1.5
# Machine Z when nut would contact tool setter, used to calculate tool offset
TOOLSET_HEIGHT = 80

# Position to rapid to for manual tool changes
MANUAL_CHANGE_X = 580
MANUAL_CHANGE_Y = 0

# motion.digital-out-xx to trigger manual tool change UI
#   -1 disables manual tool changes
TOOL_CHANGE_DO = 1
# motion.digital-in-xx indicating manual tool change complete
#   -1 disables manual tool changes
TOOL_CHANGED_DI = 1

